const faqs = [
  {
    question: "What is a Demon Name Generator?",
    answer: "A Demon Name Generator is a free online tool that creates unique and powerful names for demonic characters. It combines elements from mythology, dark fantasy, and supernatural lore to generate names suitable for both male and female demon characters, perfect for writers, gamers, and creative storytellers."
  },
  {
    question: "How does the Demon Name Generator work?",
    answer: "Our Demon Name Generator uses a sophisticated algorithm that combines mythological elements, ancient languages, and dark fantasy themes. Simply select your preferred gender (male, female, or random), click the 'Generate' button, and instantly receive unique demon names. Each name is crafted to evoke the power and mystique of supernatural beings."
  },
  {
    question: "Can I use these demon names in my creative work?",
    answer: "Yes! All names generated by our Demon Name Generator are free to use in your creative projects, whether it's for writing, gaming, role-playing, or any other creative endeavor. The names are uniquely generated and not copyrighted, making them perfect for your characters in stories, games, or other creative works."
  },
  {
    question: "What makes a good demon name?",
    answer: "A good demon name typically incorporates elements that suggest power, mystery, and otherworldliness. This can include harsh consonants (like K, X, Z), mythological references, or dark themes. Our Demon Name Generator creates names that balance these elements while maintaining pronounceability and memorability."
  },
  {
    question: "Are the generated names based on real mythology?",
    answer: "The names generated by our Demon Name Generator are inspired by various mythological sources, including ancient demons, fallen angels, and supernatural beings from different cultures. While not directly copied from existing mythology, they incorporate elements and patterns found in traditional demonic naming conventions across various cultures and belief systems."
  },
  {
    question: "Can I generate multiple demon names at once?",
    answer: "Yes! Our Demon Name Generator creates multiple unique demon names with each click. This feature is particularly useful when you need several character names for your story, game, or creative project. You can generate new sets of names as many times as you want, completely free."
  },
  {
    question: "Why use gender-specific demon names?",
    answer: "Different genders in demon names can help create more diverse and nuanced characters. Male demon names often emphasize power and dominance, while female demon names might blend elegance with darkness. Our Demon Name Generator offers both options, plus a random choice, to suit your specific character needs."
  },
  {
    question: "Where can I use these demon names?",
    answer: "These generated demon names are perfect for various creative applications, including: fantasy novels and short stories, role-playing games (RPGs), video game characters, Dungeons & Dragons campaigns, creative writing projects, comic books and graphic novels, and any other medium where supernatural characters appear. Whether you're a writer, a gamer, or a storyteller, our Demon Name Generator has got you covered!"
  }
]

export default function FAQ() {
  return (
    <section className="py-16 px-4 bg-gray-800" id="faq">
      <div className="container mx-auto max-w-4xl">
        <h2 className="text-3xl font-bold text-center mb-12 bg-gradient-to-r from-red-500 to-purple-600 bg-clip-text text-transparent">
          Frequently Asked Questions
        </h2>
        
        <div className="space-y-8">
          {faqs.map((faq, index) => (
            <div key={index} className="bg-gray-700/30 p-6 rounded-lg border border-gray-700">
              <h3 className="text-xl font-semibold mb-4 text-purple-400">
                {faq.question}
              </h3>
              <p className="text-gray-300 leading-relaxed">
                {faq.answer}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
